### ISSUE TITLE
Type promotion in comparison

### ISSUE THREAD

**Issue by timoalho** [johnmcfarlane/fixed_point#123]
Comparison by promoting to the common type with the largest integer range is potentially surprising and confusing. While there are several cases where this may manifest, one of them is especially unexpected for the user:

```
fixed_point<int, -15> fp{-0.2};
bool negative = fp < 0;
```

`negative` will be `false`!

One would certainly expect a simple comparison to the literal zero to give the sign of a number. There is of course a simple workaround, `fp < fixed_point<int, -15>{0}` (and the verbosity is taken care of by typedefs one should do anyway), but nonetheless the behaviour is surprising and guaranteed to produce difficult-to-trace -bugs.

To underline this, an output from a unit test testing this very behaviour:

```
..\src\fixed_point_math.cpp:42: FAILED:
  REQUIRE( fp{-0.2} < 0 )
with expansion:
  -0.199982 < 0
```

One solution is to make the default comparison a two-stage comparison, first with the promoted type and then comparing the fractional parts in case of equality. Then the fast compare could be made a named operator, opposite to what I believe is suggested [here](https://github.com/johnmcfarlane/fixed_point/issues/94).

**Comment by johnmcfarlane** [comment]
Thanks. There's nothing like a really simple example to bring a problem into focus! I hope you understand that the two-stage comparison is something that I'm very reluctant to consider. 

Frankly, I would rather truncate the top of the range and compare the values as `fixed_point<int, -15>`. Crazy though that sounds, it's closer to the behavior of `int` where truncation always affects high bits. Especially if this applied to mixed-mode int/fixed-point comparison only, it might be most palatable.

Another possibility is to promote beyond `int` in cases where the range of bits is that big. From there, there are a few options:
1. Convert to the common range if possible, in your example `fixed_point<int64_t, -15>`. 
2. Fail to compile if the range is too great, i.e. greater than 64-bits. At this point, user is forced to compare against, e.g. `fixed_point<int, -15>{0}` instead of `0`.
3. As a variation to 1), maybe drop any bits in the middle of two disconnected ranges. For example, in `fixed_point<uint8, 24> < fixed_point<uint8, -16>` these numbers could be converted to a common `uint16` type by scaling the former down by 16 bits and the later up by 16. I think the comparison would still hold. Does that sound worthwhile?

Sorry to press-gang you into matters of API design but what do you think?

**Comment by timoalho** [comment]
I take it you're reluctant to avoid the two-stage comparison because of performance? I do get that, although I'm not sure that I'm completely convinced if that warrants dismissing the option out of hand. The main performance hit would be having to always check for equality for the promoted type, the actual second comparison is only needed in the rather rare case that they compare equal. So the common code path, assuming that the compiler optimizes the code would look coarsely like this in pseudocode/pseudoassembler, for a less than comparison:

```
r1 = promote(lhs);
r2 = promote(rhs);
//The above two lines take 1-2 instructions, since the shift to be done is
//determined at compile time
cmp r1, r2 //at least on x86 and ARM updates all flags at once. 1 instruction
be second_comparison //extra jump for the two-stage case, 1 instruction more
bl less //this is the branch we have for integers too
not_less:
//lhs is not less, do something
...
less:
//lhs is less, do something
...
second_comparison:
//...compare low-order bits, takes another comparison and some shifting
... //around 3-4 instructions, shift (which is determined at compile time), cmp, and 
    // the branch on the next line
bnl not_less
b less
```

I would not be surprised for a decent compiler to optimize it this far from the trivial C++ source (that is, not doing the first equality/less than comparison again even if the source code seems to require it), and probably further (I'm pretty sure my ordering of labels is very suboptimal, some of the jumps could be avoided). So for the vast majority of cases, the cost is one conditional branch more, and you only pay for the extra shifts and second comparison in the rare case that you're actually comparing two numbers too close to see the difference in the promoted type. Even then, it's only a few instructions more. Of course, as always, one should profile, though!

If I find the time, I could write a quick benchmark and see what happens on x86 and Cortex-M3.

The comparison to a literal zero is an interesting special case though, as there no shifts or second comparisons are needed (or rather, you can shift the zero all you like!). Unfortunately I think this is not something that's possible to capture by template magic? Interestingly, if this becomes a part of the standard in the form which requires an accurate comparison (two-stage where necessary), then compiler writers can take advantage of the special case though. However, if the standard is that comparisons are not exact (the current behaviour), then this optimization is impossible since the fixed_point type must be shifted to lose the low-order bits.

Your suggestion 1. of course achieves the same purpose, when there is a larger common type. When there is, it is either an optimization or a pessimization of the two-comparison method, possibly depending on the platform and the compiler. If you end not up not having the two-stage comparison, I'm very much for your point 2, that at least moves the error to compile time instead of run time.
3. is a good trick, and should be done if no two-stage comparison.

So I think the fundamental question is, should the proposal require that comparisons are exact? It would anyway then be up to library implementers to do that as efficiently as possible (of course it would be nice to show that it is efficient in the reference implementation here).

Finally, let me argue a bit in favor of an exact comparison being the default, whether it's implemented by promotion, two-stage compare, or some other method: while there's a lot of arithmetic caveats in C++, this far in the comparison operators there's only one, that being the signed/unsigned case. Except for that, numbers are always promoted to the larger common type, including ints to floats, so that as long as you're not comparing signed to unsigned, you can be sure that a comparison of numbers, independent of the type used to represent them, always gives the exact actual ordering of the abstract numbers being represented. The fixed_point type would be a departure from that with the current behaviour.

> Sorry to press-gang you into matters of API design but what do you think?

No worries, happy to pay back for a nice library/proposal with any help I can give! 

I'm also noting a few other points that seem to be a bit unexpected/cumbersome in practice. Should I submit these as issues, and we'll discuss them there, or do you prefer e-mail/something else?

**Comment by johnmcfarlane** [comment]
I need to double check a few details regarding signage but I've come around to the idea that comparison should be accurate. However, it's not trivial to implement; this issue may remain open a little longer so let me know if it's a priority for you.

Here's the plan:
1. if the operands can be losslessly converted to a common type, this is done and the comparison is a simple comparison ot the `rep` values;
2. if they can be converted to a type where the range-reduction hack can be applied, then that is done instead (I'm referring to where the unused range in between the two used ranges is eliminated)
3. and finally if neither of the above can be performed (i.e. operands are not within the same range and cannot be widened) then a branching comparison is performed.

It's going to be pretty rare that the third option is necessary and this ensures that accuracy is consistent. How does that sound?

**Comment by johnmcfarlane** [comment]
So, a whole year after this issue was filed, I'm closing it. The original failing test is [now part of](https://github.com/johnmcfarlane/fixed_point/pull/256/files#diff-1a9e79c0d40330247fe7c7a3ebd73359R637) the test suite and passes. The case where combined range of operands exceeds promoted type does not and is expressed in [issue 257](https://github.com/johnmcfarlane/fixed_point/issues/257).
